name: cleaning_my_home
description: "Game Cleaning My House."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bonfire: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/